import { setRequestLocale } from "next-intl/server";
import { Metadata } from "next";
import FreeNanoBananaProClient from "./client";
import { getCanonicalUrlWithLocale } from "@/lib/constants";
import { Card } from "@/components/ui/card";

// SEO Meta Data from provided JSON
const META_DATA = {
  title: "Free Nano Banana Pro: Ultimate Multi-Image AI Fusion Tool",
  description: "Experience Free Nano Banana Pro on imagetovideo-ai. The advanced AI upgrade for blending 4 images and prompts into stunning visual art. Try it now!",
  keywords: "free nano banana pro, multi-image blending, AI image fusion, imagetovideo-ai, advanced AI art generator"
};

export async function generateMetadata({
  params,
}: {
  params: Promise<{ locale: string }>;
}): Promise<Metadata> {
  const { locale } = await params;

  return {
    title: META_DATA.title,
    description: META_DATA.description,
    keywords: META_DATA.keywords,
    alternates: {
      canonical: getCanonicalUrlWithLocale(locale, "photo-effects/free-nano-banana-pro"),
    },
    openGraph: {
      title: META_DATA.title,
      description: META_DATA.description,
      type: "website",
      locale: locale,
    },
    twitter: {
      card: "summary_large_image",
      title: META_DATA.title,
      description: META_DATA.description,
    },
    robots: {
      index: true,
      follow: true,
    },
  };
}

// Showcase Component
const ShowcaseGallery = ({ 
  id, 
  inputs, 
  result,
  altPrefix 
}: { 
  id: number, 
  inputs: string[], 
  result: string,
  altPrefix: string 
}) => (
  <div className="my-8">
    <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 items-center">
      {/* Inputs - 4 images grid */}
      <div className="space-y-4">
        <h4 className="text-lg font-semibold text-center lg:text-left text-muted-foreground">Input Images (1-4)</h4>
        <div className="grid grid-cols-2 gap-4">
          {inputs.map((src, idx) => (
            <div key={idx} className="relative h-full rounded-xl overflow-hidden border-2 border-dashed border-muted-foreground/20 bg-muted/5 shadow-sm hover:shadow-md transition-shadow">
              <img 
                src={src} 
                alt={`${altPrefix} Input ${idx + 1} - Reference for style, composition, or subject`}
                className="w-full h-auto object-contain"
                loading="lazy"
              />
              <div className="absolute bottom-2 left-2 bg-black/60 text-white text-xs px-2 py-1 rounded-md backdrop-blur-sm">
                Input {idx + 1}
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Result - 1 large image */}
      <div className="space-y-4">
        <h4 className="text-lg font-semibold text-center lg:text-left text-primary">AI Generated Result</h4>
        <div className="relative h-full rounded-xl overflow-hidden border-2 border-primary/20 shadow-lg bg-muted/5 group">
          <img 
            src={result} 
            alt={`${altPrefix} Result - Final AI fused artwork`}
            className="w-full h-auto object-contain group-hover:scale-105 transition-transform duration-500"
            loading="lazy"
          />
          <div className="absolute inset-0 bg-gradient-to-t from-black/20 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300 pointer-events-none" />
          <div className="absolute bottom-4 right-4 bg-primary text-primary-foreground text-sm font-medium px-3 py-1.5 rounded-full shadow-lg">
            Generated by Free Nano Banana Pro
          </div>
        </div>
      </div>
    </div>
  </div>
);

export default async function FreeNanoBananaProPage({
  params,
}: {
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  setRequestLocale(locale);

  return (
    <div className="min-h-screen bg-background">
      {/* Hero Section with Workspace */}
      <section className="border-b bg-card">
        <div className="container mx-auto px-4 py-12 text-center">
          <h1 className="text-4xl font-bold mb-4 bg-gradient-to-r from-yellow-500 to-orange-600 bg-clip-text text-transparent">
            Free Nano Banana Pro
          </h1>
          <p className="text-xl text-muted-foreground max-w-2xl mx-auto mb-8">
            The Ultimate Multi-Image Fusion AI Upgrade. Blend up to 4 images with advanced AI control.
          </p>
          <FreeNanoBananaProClient />
        </div>
      </section>

      {/* Content Section from JSON */}
      <div className="container mx-auto px-4 py-16 max-w-4xl space-y-16">
        {/* Introduction */}
        <section className="prose dark:prose-invert max-w-none">
          <h2 className="text-3xl font-bold mb-6">Free Nano Banana Pro: The Ultimate Multi-Image Fusion AI Upgrade</h2>
          <div className="text-lg text-muted-foreground space-y-4">
            <p>
              Welcome to the next evolution of digital artistry at <strong>imagetovideo-ai</strong>. If you were a fan of our previous generation tools, prepare to have your expectations shattered and rebuilt. We are proud to introduce the <strong>Free Nano Banana Pro</strong>, a significant leap forward in generative AI technology. While our earlier tools focused on singular character generation, the <strong>Free Nano Banana Pro</strong> is designed for complex, layered, and multifaceted visual synthesis. This is not just an update; it is a complete reimagining of how users can interact with AI to blend concepts, styles, and compositions.
            </p>
            <p>
              The core philosophy behind the <strong>Free Nano Banana Pro</strong> is "fusion." In the past, you might have relied on a single text prompt or a single reference image. Now, the <strong>Free Nano Banana Pro</strong> empowers you to upload up to four distinct reference images simultaneously. By combining these visual inputs with precise text prompts, you gain unprecedented control over the final output. Whether you are a concept artist looking to merge a character sketch with a specific texture, or a hobbyist trying to blend a photograph with an anime art style, the <strong>Free Nano Banana Pro</strong> is your dedicated engine for advanced visual alchemy.
            </p>
            <p>
              At <strong>imagetovideo-ai</strong>, we understand that creators need tools that grow with their skills. The <strong>Free Nano Banana Pro</strong> offers that growth path, moving beyond simple generation into the realm of professional-grade image orchestration. Join us as we explore the limitless potential of this powerful tool.
            </p>
          </div>
        </section>

        {/* Why Choose Section with Showcase 1 */}
        <section className="space-y-8">
          <div className="space-y-4">
            <h3 className="text-2xl font-bold">Why Choose Free Nano Banana Pro for Advanced Creation?</h3>
            <div className="prose dark:prose-invert text-muted-foreground">
              <p>
                The digital art landscape is crowded with basic text-to-image generators, but the <strong>Free Nano Banana Pro</strong> stands apart by offering a sophisticated "image-to-image" workflow that is rarely seen in free tools. Why should you choose the <strong>Free Nano Banana Pro</strong> over standard generators? The answer lies in control and complexity. Standard tools often hallucinate details or struggle to adhere to a specific visual structure. However, because the <strong>Free Nano Banana Pro</strong> accepts multiple visual inputs, it anchors the AI's imagination to the references you provide, resulting in higher fidelity and relevance.
              </p>
              <p>
                Furthermore, the <strong>Free Nano Banana Pro</strong> utilizes an advanced blending algorithm. This isn't just overlaying images; the AI analyzes the semantic content of up to four uploads—identifying lighting, structure, color palettes, and subjects—and synthesizes them into a coherent new whole. This makes the <strong>Free Nano Banana Pro</strong> an essential tool for users who have a specific vision that cannot be described by words alone.
              </p>
            </div>
          </div>

          <Card className="p-6 bg-muted/30">
            <div className="text-center mb-4">
              <h4 className="text-xl font-semibold">See It In Action: Complex Scene Synthesis</h4>
              <p className="text-sm text-muted-foreground">Blending distinct elements into a cohesive masterpiece</p>
            </div>
            <ShowcaseGallery 
              id={1}
              inputs={[
                "/imgs/showcases/free-nano-banana-pro-example-1-input-1.webp",
                "/imgs/showcases/free-nano-banana-pro-example-1-input-2.webp",
                "/imgs/showcases/free-nano-banana-pro-example-1-input-3.webp",
                "/imgs/showcases/free-nano-banana-pro-example-1-input-4.webp"
              ]}
              result="/imgs/showcases/free-nano-banana-pro-example-1-result.webp"
              altPrefix="Free Nano Banana Pro Scene Synthesis"
            />
          </Card>
        </section>
        
        {/* Mastering Fusion Section with Showcase 2 */}
        <section className="space-y-8">
          <div className="space-y-4">
            <h3 className="text-2xl font-bold">Mastering Multi-Image Fusion with Free Nano Banana Pro</h3>
            <div className="prose dark:prose-invert text-muted-foreground">
              <p>
                The defining feature of this upgraded tool is its ability to handle up to four distinct image slots. Mastering the <strong>Free Nano Banana Pro</strong> requires understanding how to utilize these slots effectively. Unlike our previous single-input tools, the <strong>Free Nano Banana Pro</strong> treats each image as a "weight" in the final calculation. You can think of it as mixing paint: one image might provide the composition, another the color scheme, a third the character design, and the fourth the texture.
              </p>
              <p>
                This multi-slot capability transforms the <strong>Free Nano Banana Pro</strong> into a powerful brainstorming partner. You are no longer generating random images; you are "directing" the AI. By mastering the input balance in the <strong>Free Nano Banana Pro</strong>, you can achieve consistency across different generations, a feat that is notoriously difficult with standard text-prompt AI.
              </p>
            </div>
          </div>

          <Card className="p-6 bg-muted/30">
            <div className="text-center mb-4">
              <h4 className="text-xl font-semibold">Character & Style Fusion</h4>
              <p className="text-sm text-muted-foreground">Merging character design with specific artistic styles</p>
            </div>
            <ShowcaseGallery 
              id={2}
              inputs={[
                "/imgs/showcases/free-nano-banana-pro-example-2-input-1.webp",
                "/imgs/showcases/free-nano-banana-pro-example-2-input-2.webp",
                "/imgs/showcases/free-nano-banana-pro-example-2-input-3.webp",
                "/imgs/showcases/free-nano-banana-pro-example-2-input-4.webp"
              ]}
              result="/imgs/showcases/free-nano-banana-pro-example-2-result.webp"
              altPrefix="Free Nano Banana Pro Character Fusion"
            />
          </Card>
        </section>

        {/* Text and Visuals */}
        <section className="space-y-4">
          <h2 className="text-3xl font-bold">Combining Text and Visuals in Free Nano Banana Pro</h2>
          <div className="prose dark:prose-invert max-w-none text-muted-foreground">
            <p>
              While the multi-image feature is the star of the show, the text prompt engine within the <strong>Free Nano Banana Pro</strong> remains a crucial component of the creative process. The true magic happens when you combine your four reference images with a descriptive text prompt. The <strong>Free Nano Banana Pro</strong> uses the text to understand the "intent" behind the images. For example, if you upload four images of forests, the AI knows the subject is a forest. But if you type "mystical glowing forest at night" into the <strong>Free Nano Banana Pro</strong> prompt bar, it knows exactly how to interpret those reference images.
            </p>
            <p>
              Text prompts in the <strong>Free Nano Banana Pro</strong> act as a guiding vector. They can override certain visual elements or emphasize others. If you upload a photo of a person and a photo of a lion, the <strong>Free Nano Banana Pro</strong> might blend them in various ways. However, adding the prompt "hybrid warrior wearing lion armor" tells the <strong>Free Nano Banana Pro</strong> exactly how to fuse those visual concepts. This synergy between textual instruction and visual reference is what makes the <strong>Free Nano Banana Pro</strong> so versatile.
            </p>
          </div>
        </section>

        {/* Applications and Upgrading */}
        <section className="grid md:grid-cols-2 gap-8">
          <div className="space-y-4">
            <h3 className="text-2xl font-bold">Creative Applications</h3>
            <div className="prose dark:prose-invert text-muted-foreground">
              <p>
                The versatility of the <strong>Free Nano Banana Pro</strong> opens up a plethora of creative applications that go far beyond simple character generation. Architects and interior designers, for instance, are using the <strong>Free Nano Banana Pro</strong> to blend sketches of room layouts with photographs of specific furniture styles and color palettes.
              </p>
              <p>
                Fashion designers are another group benefiting from the upgrade. They can use the <strong>Free Nano Banana Pro</strong> to merge fabric textures with dress sketches. By uploading a pattern swatch and a silhouette drawing, the <strong>Free Nano Banana Pro</strong> can generate a realistic preview of the garment.
              </p>
            </div>
          </div>

          <div className="space-y-4">
            <h3 className="text-2xl font-bold">Upgrading from Basic Generators</h3>
            <div className="prose dark:prose-invert text-muted-foreground">
              <p>
                Many of our users started their journey with our basic anime figure generator. While that tool served its purpose well for single-subject creation, upgrading to the <strong>Free Nano Banana Pro</strong> represents a shift from "generation" to "composition."
              </p>
              <p>
                Unlike the basic generator, which often produced generic results, the <strong>Free Nano Banana Pro</strong> produces bespoke imagery. Because the output is derived from your specific combination of up to four images, the likelihood of someone else generating the exact same image with the <strong>Free Nano Banana Pro</strong> is astronomically low.
              </p>
            </div>
          </div>
        </section>

        {/* How to Use & Settings */}
        <section className="space-y-6">
          <h2 className="text-3xl font-bold">How to Use Free Nano Banana Pro</h2>
          <div className="bg-muted/30 p-6 rounded-xl space-y-4">
            <h3 className="text-xl font-semibold">Getting Started</h3>
            <p className="text-muted-foreground">
              Getting started with the <strong>Free Nano Banana Pro</strong> on our platform is a straightforward process designed to get you creating immediately. First, navigate to the <strong>imagetovideo-ai</strong> homepage and select the <strong>Free Nano Banana Pro</strong> from the tools menu. You will see the main interface featuring the prompt text box and the four distinct image upload areas.
            </p>
            <h3 className="text-xl font-semibold mt-4">Optimizing Results</h3>
            <p className="text-muted-foreground">
              To truly unlock the potential of the <strong>Free Nano Banana Pro</strong>, one must dive into the optimization settings. While the default settings yield great results, tweaking the parameters can take your art to the professional level. Another optimization technique involves image resolution and aspect ratio. The <strong>Free Nano Banana Pro</strong> performs best when the uploaded images share a similar aspect ratio to the desired output.
            </p>
          </div>
        </section>

        {/* FAQ Section */}
        <section className="space-y-6">
          <h2 className="text-3xl font-bold text-center">Frequently Asked Questions</h2>
          <div className="grid md:grid-cols-2 gap-6">
            <div className="space-y-4">
              <div>
                <h4 className="font-bold">Q: What makes Free Nano Banana Pro different from the Anime Figure Generator?</h4>
                <p className="text-sm text-muted-foreground">A: The Anime Figure Generator was designed for single-input character creation. The <strong>Free Nano Banana Pro</strong> is an advanced multi-image fusion tool that allows you to blend up to four distinct images and text prompts for complex compositions in any style, not just anime.</p>
              </div>
              <div>
                <h4 className="font-bold">Q: Is the Free Nano Banana Pro truly free to use on imagetovideo-ai?</h4>
                <p className="text-sm text-muted-foreground">A: Yes, the standard version of the <strong>Free Nano Banana Pro</strong> is available for free users, allowing you to explore multi-image blending without an upfront cost.</p>
              </div>
              <div>
                <h4 className="font-bold">Q: How many images can I upload to the Free Nano Banana Pro at once?</h4>
                <p className="text-sm text-muted-foreground">A: You can upload a maximum of four reference images into the <strong>Free Nano Banana Pro</strong> interface to create a single fused output.</p>
              </div>
              <div>
                <h4 className="font-bold">Q: Can I use the Free Nano Banana Pro for commercial projects?</h4>
                <p className="text-sm text-muted-foreground">A: Usage rights depend on the specific terms of service on <strong>imagetovideo-ai</strong> at the time of generation. Generally, original creations made with the <strong>Free Nano Banana Pro</strong> belong to the creator, but please check our legal section for commercial specifics.</p>
              </div>
            </div>
            <div className="space-y-4">
              <div>
                <h4 className="font-bold">Q: Does the Free Nano Banana Pro work on mobile devices?</h4>
                <p className="text-sm text-muted-foreground">A: Absolutely. The <strong>Free Nano Banana Pro</strong> interface is fully responsive and optimized for mobile browsers, allowing you to blend images on the go.</p>
              </div>
              <div>
                <h4 className="font-bold">Q: Do I need a text prompt if I upload 4 images to Free Nano Banana Pro?</h4>
                <p className="text-sm text-muted-foreground">A: While not strictly mandatory, we highly recommend using a text prompt. The text helps the <strong>Free Nano Banana Pro</strong> understand how you want the four images to relate to one another (e.g., "blend style," "merge characters").</p>
              </div>
              <div>
                <h4 className="font-bold">Q: What file formats does the Free Nano Banana Pro support for uploads?</h4>
                <p className="text-sm text-muted-foreground">A: The <strong>Free Nano Banana Pro</strong> supports standard image formats including JPG, PNG, and WEBP for your reference uploads.</p>
              </div>
              <div>
                <h4 className="font-bold">Q: Can I save my blending settings in Free Nano Banana Pro?</h4>
                <p className="text-sm text-muted-foreground">A: Currently, the <strong>Free Nano Banana Pro</strong> allows you to view your generation history on <strong>imagetovideo-ai</strong>, where you can see the prompts and images used for previous creations.</p>
              </div>
            </div>
          </div>
        </section>
      </div>
    </div>
  );
}
